# https://fallguysultimateknockout.gamepedia.com/Rounds

rounds_info_dict = {
    # Race
    'round_biggestfan': {'Name': 'Big Fans', 
                         'Type': 'Race', 
                         'Introduced': 2},
    'round_gauntlet_02': {'Name': 'Dizzy Heights', 
                          'Type': 'Race', 
                          'Introduced': 1},
    'round_door_dash': {'Name': 'Door Dash', 
                        'Type': 'Race', 
                        'Introduced': 1},
    'round_dodge_fall': {'Name': 'Fruit Chute', 
                         'Type': 'Race', 
                         'Introduced': 1},
    'round_chompchomp': {'Name': 'Gate Crash', 
                         'Type': 'Race', 
                         'Introduced': 1},
    'round_gauntlet_01': {'Name': 'Hit Parade', 
                          'Type': 'Race', 
                          'Introduced': 1},
    'round_see_saw': {'Name': 'See Saw', 
                      'Type': 'Race', 
                      'Introduced': 1},
    'round_lava': {'Name': 'Slime Climb', 
                   'Type': 'Race', 
                   'Introduced': 1},
    'round_tip_toe': {'Name': 'Tip Toe', 
                      'Type': 'Race', 
                      'Introduced': 1},
    'round_gauntlet_03': {'Name': 'The Whirlygig', 
                          'Type': 'Race', 
                          'Introduced': 1},
    'round_gauntlet_04': {'Name': 'Knight Fever', 
                          'Type': 'Race', 
                          'Introduced': 2},
    'round_wall_guys': {'Name': 'Wall Guys', 
                        'Type': 'Race', 
                        'Introduced': 2},
    'round_iceclimb': {'Name': 'Freezy Peak', 
                       'Type': 'Race', 
                       'Introduced': 3},
    'round_skeefall': {'Name': 'Ski Fall', 
                       'Type': 'Race', 
                       'Introduced': 3},
    'round_gauntlet_05': {'Name': 'Tundra Run', 
                          'Type': 'Race', 
                          'Introduced': 3},
    'round_gauntlet_06': {'Name': 'Skyline Stumble', 
                          'Type': 'Race', 
                          'Introduced': 4},
    'round_shortcircuit': {'Name': 'Short Circuit', 
                           'Type': 'Race', 
                           'Introduced': 4},
    'round_tunnel_race': {'Name': 'Roll On', 
                          'Type': 'Race', 
                          'Introduced': 4},
    'round_slimeclimb_2': {'Name': 'The Slimescraper', 
                           'Type': 'Race', 
                           'Introduced': 4},
    
    
    # Survival
    'round_block_party': {'Name': 'Block Party', 
                          'Type': 'Survival', 
                          'Introduced': 1},
    'round_tunnel': {'Name': 'Roll Out', 
                     'Type': 'Survival', 
                     'Introduced': 1},
    'round_jump_club': {'Name': 'Jump Club', 
                        'Type': 'Survival', 
                        'Introduced': 1},
    'round_snowballsurvival': {'Name': 'Snowball Survival', 
                               'Type': 'Survival', 
                               'Introduced': 3},
    'round_fruitpunch': {'Name': 'Big Shots', 
                         'Type': 'Survival', 
                         'Introduced': 4},
    'round_hoverboardsurvival': {'Name': 'Hoverboard Heroes', 
                                 'Type': 'Survival', 
                                 'Introduced': 4},
    # "Special" Shows (all or mostly one map)
    'round_floor_fall_event_only_01': {'Name': 'Hex-A-Gone 1 (Hex-a-gone Trials)', 'Type': 'Survival', 'Introduced': 3},
    'round_floor_fall_event_only_02': {'Name': 'Hex-A-Gone 2 (Hex-a-gone Trials)', 'Type': 'Survival', 'Introduced': 3},
    
    'round_jump_club_event_only_01': {'Name': 'Jump Club 1 (Jump Around)', 'Type': 'Survival', 'Introduced': 3},
    'round_jump_club_event_only_02': {'Name': 'Jump Club 2 (Jump Around)', 'Type': 'Survival', 'Introduced': 3},
    'round_jump_club_event_only_03': {'Name': 'Jump Club 3 (Jump Around)', 'Type': 'Survival', 'Introduced': 3},
    
    'round_thin_ice_event_only_01': {'Name': 'Thin Ice (Thin Ice Trials)', 'Type': 'Survival', 'Introduced': 3},
    'round_thin_ice_event_only_02': {'Name': 'Thin Ice (Thin Ice Trials)', 'Type': 'Survival', 'Introduced': 3},
    
    'round_lava_event_only_slime_climb_01': {'Name': 'Slime Climb 1 (SCT)', 'Type': 'Race', 'Introduced': 4},
    'round_lava_event_only_slime_climb_02': {'Name': 'Slime Climb 2 (SCT)', 'Type': 'Race', 'Introduced': 4},
    'round_lava_event_only_slime_climb_03': {'Name': 'Slime Climb 3 (SCT)', 'Type': 'Race', 'Introduced': 4},
    
    'round_event_only_basketfall_01': {'Name': 'Basketfall (Slam Dunk)', 'Type': 'Team', 'Introduced': 4},
    'round_event_only_basketfall_02': {'Name': 'Basketfall (Slam Dunk)', 'Type': 'Team', 'Introduced': 4},
    
    'round_tunnel_event_only_roll_out_01': {'Name': 'Roll Out 1 (Roll Call)', 'Type': 'Survival', 'Introduced': 4},
    'round_tunnel_event_only_roll_out_02': {'Name': 'Roll Out 2 (Roll Call)', 'Type': 'Survival', 'Introduced': 4},
    'round_tunnel_event_only_roll_out_03': {'Name': 'Roll Out 3 (Roll Call)', 'Type': 'Survival', 'Introduced': 4},
    
    'round_fall_ball_cup_only_01': {'Name': 'Fall Ball 1 (Fall Ball Cup)', 'Type': 'Team', 'Introduced': 3}, 
    'round_fall_ball_cup_only_02': {'Name': 'Fall Ball 2 (Fall Ball Cup)', 'Type': 'Team', 'Introduced': 3},
    'round_fall_ball_cup_only_03': {'Name': 'Fall Ball 3 (Fall Ball Cup)', 'Type': 'Team', 'Introduced': 3},
    
    'round_floor_fall_event_only_low_grav_01': {'Name': 'Hex-A-Gone 1 (Hex-a-4041 Trials)', 'Type': 'Survival', 'Introduced': 4},
    'round_floor_fall_event_only_low_grav_02': {'Name': 'Hex-A-Gone 2 (Hex-a-4041 Trials)', 'Type': 'Survival', 'Introduced': 4},
    
    'round_slimeclimb_2_event_only_01': {'Name': 'The Slimescraper 1 (Slimescraper Time)', 'Type': 'Race', 'Introduced': 4},
    'round_slimeclimb_2_event_only_02': {'Name': 'The Slimescraper 2 (Slimescraper Time)', 'Type': 'Race', 'Introduced': 4},
    
    
    # Hunt
    'round_tail_tag': {'Name': 'Tail Tag', 
                       'Type': 'Hunt', 
                       'Introduced': 1},
    'round_hoops_blockade_solo': {'Name': 'Hoopsie Legends', 
                                  'Type': 'Hunt', 
                                  'Introduced': 2},
    'round_1v1_button_basher': {'Name': 'Button Bashers', 
                                'Type': 'Hunt', 
                                'Introduced': 4},
    
    # Logic
    'round_match_fall': {'Name': 'Perfect Match', 
                         'Type': 'Logic', 
                         'Introduced': 1},
    
    # Team
    'round_egg_grab': {'Name': 'Egg Scramble', 
                       'Type': 'Team', 
                       'Introduced': 1},
    'round_fall_ball_60_players': {'Name': 'Fall Ball', 
                                   'Type': 'Team', 
                                   'Introduced': 1},
    'round_ballhogs': {'Name': 'Hoarders', 
                       'Type': 'Team', 
                       'Introduced': 1},
    'round_hoops': {'Name': 'Hoopsie Daisy', 
                    'Type': 'Team', 
                    'Introduced': 1},
    'round_jinxed': {'Name': 'Jinxed', 
                     'Type': 'Team', 
                     'Introduced': 1},
    'round_conveyor_arena': {'Name': 'Team Tail Tag', 
                             'Type': 'Team', 
                             'Introduced': 1},
    'round_rocknroll': {'Name': "Rock 'N' Roll", 
                        'Type': 'Team', 
                        'Introduced': 1},
    'round_egg_grab_02': {'Name': 'Egg Siege', 
                          'Type': 'Team', 
                          'Introduced': 2},
    'round_snowy_scrap': {'Name': 'Snowy Scrap', 
                          'Type': 'Team', 
                          'Introduced': 3},
    'round_chicken_chase': {'Name': 'Pegwin Pursuit', 
                            'Type': 'Team', 
                            'Introduced': 3},
    'round_basketfall': {'Name': 'Basketfall', 
                         'Type': 'Team', 
                         'Introduced': 4},
    'round_territory_control': {'Name': 'Power Trip', 
                                'Type': 'Team', 
                                'Introduced': 4},
    
    # Finals
    'round_jump_showdown': {'Name': 'Jump Showdown', 
                            'Type': 'Final', 
                            'Introduced': 1},
    'round_floor_fall': {'Name': 'Hex-A-Gone', 
                         'Type': 'Final', 
                         'Introduced': 1},
    'round_fall_mountain_hub_complete': {'Name': 'Fall Mountain', 
                                         'Type': 'Final', 
                                         'Introduced': 1},
    'round_royal_rumble': {'Name': 'Royal Fumble', 
                           'Type': 'Final', 
                           'Introduced': 1}, 
    'round_thin_ice': {'Name': 'Thin Ice', 
                       'Type': 'Final', 
                       'Introduced': 3},
    'round_tunnel_final': {'Name': 'Roll Off', 
                           'Type': 'Final', 
                           'Introduced': 3},
    'round_floor_fall_event_only_final': {'Name': 'Hex-A-Gone Final (Hex-a-gone Trials)', 
                                          'Type': 'Final', 
                                          'Introduced': 3},
    'round_jump_showdown_jump_club_event_only_final': {'Name': 'Jump Showdown (Jump Around)', 
                                                       'Type': 'Final', 
                                                       'Introduced': 3},
    'round_thin_ice_event_only_final': {'Name': 'Thin Ice (Thin Ice Trials)', 
                                        'Type': 'Final', 
                                        'Introduced': 3},
    'round_lava_event_only_slime_climb_final': {'Name': 'Slime Climb 1 (SCT)', 
                                                'Type': 'Final', 
                                                'Introduced': 4},
    'round_tunnel_event_only_roll_out_final': {'Name': 'Roll Off (Roll Call)', 
                                               'Type': 'Final', 
                                               'Introduced': 4},
    'round_floor_fall_event_only_low_grav_final': {'Name': 'Hex-A-Gone Final (Hex-a-4041 Trials)', 
                                                   'Type': 'Final', 
                                                   'Introduced': 4},
    'round_slimeclimb_2_event_only_final': {'Name': 'The Slimescraper Final (Slimescraper Time)', 
                                            'Type': 'Final', 
                                            'Introduced': 4},
}

# '': {'Name': '', 'Type': '', 'Introduced': 4},

# at some point figure out where/if this is used
list_of_finals = ['round_fall_mountain', 'round_floor_fall', 'round_royal_rumble', 'round_jump_showdown', 
                  'round_fall_mountain_hub_complete', 'round_thin_ice', 'round_tunnel_final', 
                  'round_floor_fall_event_only_final', 'round_jump_showdown_jump_club_event_only_final', 
                  'round_thin_ice_event_only_final']

# somewhat maintained
# maybe redo this to get rid of the dates part
# could test for inclusion elsewhere
show_type_dict = {
    'main_show': 'Main Show',
    'event_only_survival_3010_to_0511': 'Slime Survivors',
    'event_only_season_2_variation_1011_to_1611': 'Medieval Mix Up',
    'event_only_hard_mode_2111_to_2711': 'Hard Mode',
    'event_season_3_highlight_1512_to_1912': 'Season 3',
    'event_only_floor_fall_0501_to_0701': 'Hex-a-gone Trials',
    'event_only_jump_club_1202_to_1402_2021': 'Jump Around',
    'event_only_thin_ice_1903_to_2203_2021': 'Thin Ice Trials',
    'event_only_season_4_2203_to_2803_2021': 'FG 4041',
    'event_twitch_rivals_2303_2021': 'Twitch Rivals',
    'squads_4player_2203_to_0404_2021': 'Squads Mode',
    'event_only_basketfall_2903_to_3103_2021': 'Slam Dunk',
    'event_only_slime_climb_0504_to_0804_2021': 'Slime Climb Time',
    'event_only_roll_out_1504_to_1704_2021': 'Roll Call',
    'event_only_hard_mode_2104_to_2404_2021': 'Hard Mode',
    'event_yeetus_0305_to_0605_2021': 'Big Yeetus Tour',
    'event_only_fall_ball_1005_to_1205_2021': 'Fall Ball Cup',
    'event_xtreme_fall_guys_2005_to_2205_2021': 'X-treme Fall Guys',
    'event_fanfare_2305_to_2605_2021': 'Blow Up',
    'event_only_floor_fall_low_grav_0306_to_0606_2021': 'Hex-a-4041 Trials',
    'event_no_teams_1406_to_1606_2021': 'No Teams',
    'event_only_slime_climb_2_1706_to_2006_2021': 'Slimescraper Time',
}

show_type_dict_v2 = {
    'main_show': 'Main Show',
    'event_only_survival': 'Slime Survivors',
    'event_only_season_2': 'Medieval Mix Up',
    'event_only_hard_mode': 'Hard Mode',
    'event_season_3_highlight': 'Season 3',
    'event_only_floor_fall': 'Hex-a-gone Trials',
    'event_only_jump_club': 'Jump Around',
    'event_only_thin_ice': 'Thin Ice Trials',
    'event_only_season_4': 'FG 4041',
    'event_twitch_rivals': 'Twitch Rivals',
    'squads_4player': 'Squads Mode',
    'event_only_basketfall': 'Slam Dunk',
    'event_only_slime_climb': 'Slime Climb Time',
    'event_only_roll_out': 'Roll Call',
    'event_yeetus': 'Big Yeetus Tour',
    'event_only_fall_ball': 'Fall Ball Cup',
    'event_xtreme_fall_guys': 'X-treme Fall Guys',
    'event_fanfare': 'Blow Up',
    'event_only_floor_fall_low_grav': 'Hex-a-4041 Trials',
    'event_no_teams': 'No Teams',
    'event_only_slime_climb_2': 'Slimescraper Time',
}

# all possible starting races in a normal round
# could grab all round 0 maps for the main_show mode
starting_races = ['round_biggestfan', 'round_gauntlet_02', 'round_door_dash', 
                  'round_chompchomp', 'round_gauntlet_01', 'round_see_saw', 
                  'round_gauntlet_03', 'round_gauntlet_04', 'round_gauntlet_05', 
                  'round_gauntlet_06', 'round_tunnel_race']

# special shows (aka shows that are all the "same"/a similar round, like all Thin Ice)
special_shows = ['event_only_floor_fall', 'event_only_jump_club', 'event_only_thin_ice', 
                 'event_only_basketfall', 'event_only_slime_climb', 'event_only_roll_out']

